### ISSUE TITLE
实测三星note5 6.0 ，华为荣耀7 5.0

### ISSUE THREAD

**Issue by allenymt** [D-clock/AndroidDaemonService#1]
## 博主 ，你好，在华为荣耀7 5.0系统上实测：Bad notification for startForeground: java.lang.RuntimeException: icon must be non-zero，会抛出这个错，意思是Notification不能为空，用微信试了了下，发现他们确实把进程优先级提高到1（关掉界面后），不知道是怎么做的

给Notification加了图片后通知栏里就有消息了

----说下测试情况---
白色Service那个能看到isForgound已经为true了,一旦退出程序，优先级还是8（华为荣耀7）（三星的是6，这个跟系统有关），微信的优先级在退出后就是1，目前猜测：像博主说的，微信和rom厂商有合作

**Comment by D-clock** [comment]
@allenyulun 没有在华为荣耀7 5.0的环境测试过，能否留个联系方式？修完bug后协助一下测试

**Comment by wenzhijie** [comment]
我用的灰色模式，感觉有些可以完善些，正在做这块内容，查了些资料，不知道以下说的对否，若有不对，请指正：
1、service的onStartCommand中，是否需要加入返回START_STICKY，以便内存不足自行重启；
2、AndroidManifest中，应用参数设置是否有必要android:persistent="true"，提高优先级；
3、service中是否需要重写onTrimMemory（），提高内存不足时重启概率；

目前这几点都是看其他各种资料总结的，也不知道对不对

**Comment by D-clock** [comment]
@wenzhijie android:persistent="true"这个对普通应用是没有效果的，系统应用才有效！START_STICKY是可以加的，你打印ServiceRecord的信息出来可以看到有些应用的Service有重启的次数。onTrimMemory这点没错，需要在内存低的时候尽量释放内存，避免被杀！

**Comment by allenymt** [comment]
@D-clock  扣扣：804445159,后来找了4.2的机子是可以的~

**Comment by D-clock** [comment]
@allenyulun 好嘞，先多谢先，这几天整一下，到时候有劳你帮我测试验证一下！

**Comment by D-clock** [comment]
@allenyulun Hello，我已经更新了最新代码，在华为的机子，6.0的系统上跑过，没有报错。你可以试试还有没有问题。另外也验证了你说微信退到后台oom_adj=1的问题，详细细节已经在README中说明！

**Comment by D-clock** [comment]
@allenyulun @wenzhijie Hello，我已经更新最新代码啦，大家可以验证一下自己的机子有没有问题！有问题可以继续反馈！
