### ISSUE TITLE
关于进程保活的疑问

### ISSUE THREAD

**Issue by ruijun** [D-clock/AndroidDaemonService#10]
@D-clock 
你好，运行代码后，有几个问题要请教下你：
- 主进程：com.clock.daemon 
- 普通后台进程：com.clock.daemon:bg

发现这两个进程被干掉(使用LBE或者AS操作)后，过一会就重启了。它们是怎样被重启起来的呢？

**Comment by D-clock** [comment]
利用 AlarmManager 发送广播拉起进程！

**Comment by ruijun** [comment]
@D-clock UI进程被干掉之后，也是靠AlarmManager 发送广播拉起进程？

**Comment by D-clock** [comment]
@ruijun Yes！或者也可以利用其他系统的广播来拉起！
