### ISSUE TITLE
小米手机显示前台进程“XX正在运行”

### ISSUE THREAD

**Issue by haofei91** [D-clock/AndroidDaemonService#11]
多部小米手机 会出现“XX正在运行”的提示，求破解，求回复~~~

**Comment by D-clock** [comment]
@haofei91 这个我也不大清楚情况，手头只有一台红米测试机，是没有问题的，多部小米是指什么机子，还有MIUI版本多少，以及Android系统版本呢？

**Comment by haofei91** [comment]
感谢回复~~

发现原来是自己漏了注册一个内部service，现在已经修复了

另外，想问下，到底需要在内部service中stopForeground(true);么？
