### ISSUE TITLE
魅族小米系列android5.0^最近任务栏划掉后在“正在运行”栏目中找不到服务

### ISSUE THREAD

**Issue by gogeer** [D-clock/AndroidDaemonService#2]

**Comment by wenzhijie** [comment]
魅族我放弃了，我这两天也在做这个，用三星的测试，现在已经后台一天了，魅族的不行，半小时就没了。不过我测试的是mx3，android4.4，好像5.0系统以后删除的是进程组，而不是单独一个进程， 一删这两个进程就都没了

**Comment by gogeer** [comment]
三星我测了的确可以；5.0以后删除进程组，能不能让它们不在一个进程组，或者像正点闹钟那样，后台服务停止停止，但还是有Notifiction;或者是像360那样；在小米系列别清掉后一段时间；又自动重新启动

**Comment by wenzhijie** [comment]
1、360这样的软件，系统应该设置成了白名单吧，至少魅族里360就直接内置成系统安全应用。
2、不在进程组里，那也就是另一个应用了吧，你再做个test应用，让这两个应用相互监听唤醒试试，不过安装时怎么操作，一次装两个应用么；

**Comment by gogeer** [comment]
在饮用在启动一个native进程；在native进程中监听应用；这样行不行；还有待验证。我最近也在做类适于这样的东西；一直没有找到突破口

**Comment by D-clock** [comment]
@yanggaosheng Native进程的，记得已经被封杀了。。之前看UC和360都有这种效果，现在没看到了！

**Comment by gogeer** [comment]
你现在还有没有其他好的想法；关于这一点上，

**Comment by gogeer** [comment]
我查看了小米平台上的权限；需要给它加上自启权限，这样久能保证在小米平台上服务不被杀

**Comment by wenzhijie** [comment]
@yanggaosheng 自起权限？是开机自起权限么？

**Comment by gogeer** [comment]
不是；是应用自启；我加上以后久可以了；需要用户主动添加才行：具体如下：
可以引导用户跳转自启动管理页面由用户手动开启。 Intent intent = new Intent(); intent.setAction("miui.intent.action.OP_AUTO_START"); intent.addCategory(Intent.CATEGORY_DEFAULT);

**Comment by gogeer** [comment]
自启动包含开机自启动和接收系统广播等方式启动，但是由A应用启动B应用则不受限制。

**Comment by gogeer** [comment]
这是小米平台的描述
http://dev.xiaomi.com/docs/appsmarket/technical_docs/adaptation_FAQ/

**Comment by D-clock** [comment]
@yanggaosheng 下面这段代码的作用是让用户跳到白名单管理界面那里，自己选择启动自启动权限吧

``` java

Intent intent = new Intent(); 
intent.setAction("miui.intent.action.OP_AUTO_START");
intent.addCategory(Intent.CATEGORY_DEFAULT);

```

**Comment by gogeer** [comment]
嗯；目前我只能这样弄；但不知道正点闹钟在这是怎么实现的；

**Comment by D-clock** [comment]
@yanggaosheng @wenzhijie Hello，我已经更新最新代码啦，大家可以验证一下自己的机子有没有问题！有问题可以继续反馈！

**Comment by wenzhijie** [comment]
@yanggaosheng  @D-clock 我突然想起来了，为什么咱们不用JNI做，那个不是所谓的终极解决方案么，从底层就分个守护进程。感觉是不是效果更好，不用单独再去考虑小米还有单独跳转至权限界面。

**Comment by D-clock** [comment]
@wenzhijie 建议不要这样做，这种做法也是不断被Google封杀掉的，而且很多大厂都不这么搞了。例如UC和360之前都在卸载完后利用JNI fork出来的进程去打开系统浏览器，早就不起作用了。况且JNI fork出进程来的代码实现难度很大，需要考虑不同版本的Android系统，还可能产生耗电问题。有兴趣可以在自己的demo中去实践探索，但强烈不建议加入到实际商业化的app中。

**Comment by gogeer** [comment]
测试过了；还是只有三星能够保存后台的服务；其它的都还是不可以

**Comment by wenzhijie** [comment]
我这测试了魅族Mx 3，也是一样的效果，坚持不到半小时

**Comment by gogeer** [comment]
4.4以后的都不行；4.4之前的前台服务就可以

**Comment by D-clock** [comment]
@yanggaosheng @wenzhijie 都在后台运行进程看不到了？是放着什么都不做就被干掉了？还是从屏幕划掉了？我用了华为荣耀6 Android6.0 和魅族MX5 Android5.0.1都没问题。。。。。

**Comment by gogeer** [comment]
从最近任务栏中划掉后；在后台运行进程中看不到；

**Comment by wenzhijie** [comment]
@yanggaosheng @D-clock 我mx3上，启动后，在进程管理器中看到两个进程已启动，然后放一边就不管了，差不多20多分钟后再在进程管理器中就看不到了。我觉得咱们加个qq群吧，这样交流也快些，讨论也方便些，毕竟这也是个技术点，基本现在app都有推送功能。

**Comment by D-clock** [comment]
@yanggaosheng 这个属于正常现象，像我那华为荣耀6 Android6.0测试的结果：微信和手Q划掉后，后台进程依然在。所以我拿了除了陌陌、微博、豌豆荚等都做了尝试，他们划掉之后，也都不行了。所以我猜测手Q和微信在华为的白名单中，我把自己的demo改成手Q的包名编译安装，结果再去划掉我的demo，发现我一直都在后台运行进程中。so，你懂的，具体的说明我在readme中写了。很多厂商定制ROM的时候改动了这个划掉的机制，有些划掉是不杀死前台进程的，有些划掉之后是会杀死的。

**Comment by D-clock** [comment]
@yanggaosheng @wenzhijie 这个好，不过我没法建群啦，要不两位童鞋加一下我Q（1084991652），我建个讨论组。加的话记得附上个人信息哈，有英文名可以加上英文名。
