### ISSUE TITLE
实测 三星s4 5.0 官方系统 加了 灰色方法后 还是显示 应用图标

### ISSUE THREAD

**Issue by 287138531** [D-clock/AndroidDaemonService#3]
实测 三星5.0 加了 灰色方法后 还是显示 应用图标。 
我在自己的服务 上添加了   灰色方法。。。状态栏就一片混乱。。。还是会有个图标在状态栏左上角

而且系统卡死。。。。。。。。。状态栏 也拉不下来了。。。。

**Comment by allenymt** [comment]
```
  5. 0 灰色保活不会报错吗？ 应该会报这个错吧：notification icon must be non-zero,5.0的试了 notification的不能为空了
```

**Comment by D-clock** [comment]
@287138531 ok，我跟进一下这个问题，这几天弄一下，有劳你到时候帮我测试验证一下！

**Comment by 287138531** [comment]
麻烦了。。最近在写个山寨的即时通迅。。。（毕业设计）
要保证 通讯服务  aidl  尽可能存活。。。。（这个存活。。没什么问题了）
现在想做到activity 不被 系统自带的那个卡片任务管理器 手动清理 掉这个 效果。。。。（qq，微信 是可以实现的。。三星系统也有白名单？）

**Comment by D-clock** [comment]
@287138531 @allenyulun Hello，我已经更新最新代码啦，大家可以验证一下自己的机子有没有问题！有问题可以继续反馈！

**Comment by 287138531** [comment]
新测试   。用灰色方法。。。。。三星s45.0 系统。。启动服务的时候 状态栏会 闪一下  应用图标。。
我有  一个    主进程     消息服务aidl进程    和这个在消息服务进程启动的灰色服务，，手动进入系统卡片 滑动清理  程序。灰色进程先挂掉。。。主进程和aidl 反而 没事。。。aidl貌似提高了一点存活率。。没加任何唤醒情况下

**Comment by xingstarx** [comment]
@D-clock   API >= 18 的平台上用的灰色保活手段，你在WakeGrayInnerService这个里面onStartCommand的方法中，怎么注释了这段代码stopForeground(true); 是因为什么原因呢

我在线上环境中，采用的是你你这个灰色保护的方案，线上某些6.0的机型是存在一些问题的，  还有Asus型号的5.0.1也是有bug

Bad notification for startForeground: java.lang.RuntimeException: icon must be non-zero

请指点下
