### ISSUE TITLE
灰色保活服务代码如何kill？

### ISSUE THREAD

**Issue by lumenghz** [D-clock/AndroidDaemonService#5]
RT，我代码中stopservice没有用，停不掉

**Comment by lumenghz** [comment]
@D-clock

**Comment by D-clock** [comment]
@lubeast 这个问题我需要跟进一下，之前并没有考虑过主动kill，一般为了做保活都不会主动kill掉！

**Comment by lumenghz** [comment]
好的，谢谢。因部分需求需要kill掉服务。感谢帮助。

**Comment by BlackHumorwj** [comment]
小米手机，垃圾清理后两个进程都木有了？灰色保洁、白色保洁都是酱紫

**Comment by D-clock** [comment]
@BlackHumorwj 正常啊，文章中已经说明了！

**Comment by catroom** [comment]
@lubeast 你可以灰色保活？我一杀就没了。。。。

**Comment by lumenghz** [comment]
@catroom 在部分国产机上是没用的，比如小米和魅族 😄 。

**Comment by catroom** [comment]
@lubeast 是我直接运行博主的demo，无论那种保活都是一杀就杀，小米魅族都是这样。。。

**Comment by lumenghz** [comment]
@catroom 别想了，且不说这种做法不推荐了，国内的手机很强悍的👍
